#lang racket

(require "declarations.rkt")

(provide buildTree)
(provide calcForces)
(provide moveparticles)

(define (sop ps)
  (define (somh ps x)
    (if (null? ps) x
        (somh (cdr ps) (+ x (particle-mass (car ps))))))
  (somh ps 0))

(define (pop ps)
  (define (pophx ps x)
    (if (null? ps) x
        (pophx (cdr ps) (+ x (* (particle-mass (car ps)) (vec-x (particle-posn (car ps))))))))
  (define (pophy ps y)
    (if (null? ps) y
        (pophy (cdr ps) (+ y (* (particle-mass (car ps)) (vec-y (particle-posn (car ps))))))))
  (vec (/ (pophx ps 0) (sop ps)) (/ (pophy ps 0) (sop ps))))

(define (ia1 ia)
  (bbox (bbox-llx ia) (bbox-lly ia) (/ (+ (bbox-llx ia) (bbox-rux ia)) 2) (/ (+ (bbox-lly ia) (bbox-ruy ia)) 2)))

(define (ia2 ia)
  (bbox (/ (+ (bbox-llx ia) (bbox-rux ia)) 2) (bbox-lly ia) (bbox-rux ia) (/ (+ (bbox-lly ia) (bbox-ruy ia)) 2)))

(define (ia3 ia)
  (bbox (/ (+ (bbox-llx ia) (bbox-rux ia)) 2) (/ (+ (bbox-lly ia) (bbox-ruy ia)) 2) (bbox-rux ia) (bbox-ruy ia)))

(define (ia4 ia)
  (bbox (bbox-llx ia) (/ (+ (bbox-lly ia) (bbox-ruy ia)) 2) (/ (+ (bbox-llx ia) (bbox-rux ia)) 2) (bbox-ruy ia)))

(define (ps1 ia ps)
  (define (ps1helper ia ps l count)
    (cond ((= count (length ps)) l)
          ((and (>= (vec-x (particle-posn (list-ref ps count))) (bbox-llx (ia1 ia)))
                (< (vec-x (particle-posn (list-ref ps count))) (bbox-rux (ia1 ia)))
                (>= (vec-y (particle-posn (list-ref ps count))) (bbox-lly (ia1 ia)))
                (< (vec-y (particle-posn (list-ref ps count))) (bbox-ruy (ia1 ia))))
           (ps1helper ia ps (append (list (list-ref ps count)) l) (+ count 1)))
          (else (ps1helper ia ps l (+ count 1)))))
  (ps1helper ia ps '() 0))

(define (ps2 ia ps)
  (define (ps2helper ia ps l count)
    (cond ((= count (length ps)) l)
          ((and (>= (vec-x (particle-posn (list-ref ps count))) (bbox-llx (ia2 ia)))
                (<= (vec-x (particle-posn (list-ref ps count))) (bbox-rux (ia2 ia)))
                (>= (vec-y (particle-posn (list-ref ps count))) (bbox-lly (ia2 ia)))
                (< (vec-y (particle-posn (list-ref ps count))) (bbox-ruy (ia2 ia))))
           (ps2helper ia ps (append (list (list-ref ps count)) l) (+ count 1)))
          (else (ps2helper ia ps l (+ count 1)))))
  (ps2helper ia ps '() 0))

(define (ps3 ia ps)
  (define (ps3helper ia ps l count)
    (cond ((= count (length ps)) l)
          ((and (>= (vec-x (particle-posn (list-ref ps count))) (bbox-llx (ia3 ia)))
                (<= (vec-x (particle-posn (list-ref ps count))) (bbox-rux (ia3 ia)))
                (>= (vec-y (particle-posn (list-ref ps count))) (bbox-lly (ia3 ia)))
                (<= (vec-y (particle-posn (list-ref ps count))) (bbox-ruy (ia3 ia))))
           (ps3helper ia ps (append (list (list-ref ps count)) l) (+ count 1)))
          (else (ps3helper ia ps l (+ count 1)))))
  (ps3helper ia ps '() 0))

(define (ps4 ia ps)
  (define (ps4helper ia ps l count)
    (cond ((= count (length ps)) l)
          ((and (>= (vec-x (particle-posn (list-ref ps count))) (bbox-llx (ia4 ia)))
                (< (vec-x (particle-posn (list-ref ps count))) (bbox-rux (ia4 ia)))
                (>= (vec-y (particle-posn (list-ref ps count))) (bbox-lly (ia4 ia)))
                (<= (vec-y (particle-posn (list-ref ps count))) (bbox-ruy (ia4 ia))))
           (ps4helper ia ps (append (list (list-ref ps count)) l) (+ count 1)))
          (else (ps4helper ia ps l (+ count 1)))))
  (ps4helper ia ps '() 0))

(define (buildTree ia ps)
  (cond ((null? ps) '())
        ((singleton ps) (car ps))
        (else (gnode (sop ps) (pop ps) (remove* '(()) (list (buildTree (ia1 ia) (ps1 ia ps))
                                                            (buildTree (ia2 ia) (ps2 ia ps))
                                                            (buildTree (ia3 ia) (ps3 ia ps))
                                                            (buildTree (ia4 ia) (ps4 ia ps))))))))
  
(define (dist_bw_two_p p1 p2)
  (sqrt (+ (expt (- (vec-x (particle-posn p1)) (vec-x (particle-posn p2))) 2)
           (expt (- (vec-y (particle-posn p1)) (vec-y (particle-posn p2))) 2))))

(define (dist_bw_p_and_gnode p gn)
  (sqrt (+ (expt (- (vec-x (particle-posn p)) (vec-x (gnode-posn gn))) 2)
           (expt (- (vec-y (particle-posn p)) (vec-y (gnode-posn gn))) 2))))

(define (len_of_sq ia)
   (- (bbox-llx ia) (bbox-rux ia))) 
              
(define (force_on_p_by_gnode p gn)
  (define (force_bw_p_and_gnode p gn) (/ (* g (particle-mass p) (gnode-mass gn)) (expt (dist_bw_p_and_gnode p gn) 3)))
  (vec (* (force_bw_p_and_gnode p gn) (- (vec-x (gnode-posn gn)) (vec-x (particle-posn p))))
       (* (force_bw_p_and_gnode p gn) (- (vec-y (gnode-posn gn)) (vec-y (particle-posn p))))))

(define (force_on_p1_by_p2 p1 p2)
  (define (force_bw_two_p p1 p2) (/ (* g (particle-mass p1) (particle-mass p2)) (expt (dist_bw_two_p p1 p2) 3)))
   (vec (* (force_bw_two_p p1 p2) (- (vec-x (particle-posn p2)) (vec-x (particle-posn p1))))
       (* (force_bw_two_p p1 p2) (- (vec-y (particle-posn p2)) (vec-y (particle-posn p1))))))

(define (add_vec v1 v2)
  (vec (+ (vec-x v1) (vec-x v2)) (+ (vec-y v1) (vec-y v2))))
 
(define (all_p_under_tree t l x)
    (cond ((= x (length (gnode-subtrees t))) l)
          ((gnode? (list-ref (gnode-subtrees t) x))
           (all_p_under_tree t (append (all_p_under_tree (list-ref (gnode-subtrees t) x) '() 0) l) (+ x 1)))
          (else (all_p_under_tree t (append (list (list-ref (gnode-subtrees t) x)) l) (+ x 1)))))
     
(define (calcForceshelper t p)
  (define ps (all_p_under_tree t '() 0))
  (define ia (bounding-box ps))
  (define l1 (gnode-subtrees t))
  (define (cfhh t p l x)
  (cond ((> (/ (dist_bw_p_and_gnode p t) (len_of_sq ia)) theta) (list t)) 
        ((= x (length l1)) l)
        (else (if (gnode? (list-ref l1 x)) (cfhh t p (append (calcForceshelper (list-ref l1 x) p) l) (+ x 1))
                  (cfhh t p (append (list (list-ref l1 x)) l) (+ x 1))))))
   (remove p (cfhh t p '() 0)))

(define (cfh2 p gl v count)
  (cond ((= count (length gl)) v)
        ((and (gnode? (list-ref gl count)) (not (= (dist_bw_p_and_gnode p (list-ref gl count)) 0)))
         (cfh2 p gl (add_vec (force_on_p_by_gnode p (list-ref gl count)) v) (+ count 1)))
        ((and (particle? (list-ref gl count)) (not (= (dist_bw_two_p p (list-ref gl count)) 0)))
         (cfh2 p gl (add_vec (force_on_p1_by_p2 p (list-ref gl count)) v) (+ count 1)))
        (else (cfh2 p gl (add_vec (vec 0 0) v) (+ count 1)))))

(define (calcForces ia t ps)
  (define (cfh ia t ps l x)
    (cond ((= x (length ps)) l)
          (else (cfh ia t ps (append (list (cfh2 (list-ref ps x)
                                                    (calcForceshelper t (list-ref ps x))
                                                    (vec 0 0) 0)) l) (+ x 1)))))
  (reverse (cfh ia t ps '() 0)))

(define (moveparticles particles forces)
  (zipwith mph particles forces))

(define (mph p v)
  (particle (particle-mass p) (vec (+ (vec-x (particle-posn p)) (* timeslice (vec-x (particle-velocity p)))
                                      (/ (* timeslice timeslice (/ (vec-x v) (particle-mass p))) 2))
                                   (+ (vec-y (particle-posn p)) (* timeslice (vec-y (particle-velocity p)))
                                      (/ (* timeslice timeslice (/ (vec-y v) (particle-mass p))) 2)))
            (vec (+ (vec-x (particle-velocity p)) (* timeslice (/ (vec-x v) (particle-mass p))))
                 (+ (vec-y (particle-velocity p)) (* timeslice (/ (vec-y v) (particle-mass p)))))))