
occupancy(B) :- B=[[sanket,S],[ankush,AN],[ashwin,AS],[umang,U],[krishna,K]],
		member(AS,[1,2,3,4]),
		member(AN,[2,3,4,5]),
                member(U,[2,3,4]),
		member(S,[3,4,5]),
		member(K,[1,2,3,4,5]),
		K1 is K+1,
                \==(U,K1),
                U1 is U+1,
                \==(U1,K),
                AN1 is AN+1,
                \==(U,AN1),
                \==(U1,AN),
                >(S,AN),
		\==(S,AN),
                \==(S,AS),
                \==(S,U),
                \==(S,K),
                \==(AN,AS),
                \==(AN,U),
                \==(AN,K),
                \==(AS,K),
                \==(AS,U),
                \==(U,K).
